/**
 * 
 * Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */
/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
  let a = 0;
  let b = 0;
  let sLength = s.split('').length;
  let tLength = t.split('').length;
  for (let i = 0; i < sLength; i++) a += s.charCodeAt(i)
  for (let i = 0; i < tLength; i++) b += t.charCodeAt(i)
  return String.fromCharCode(b - a);
};